
services:
  server:
    build:
      context: .
      dockerfile: EventBusServer/Dockerfile
    container_name: eventbus-server
    ports:
      - "9001:9000"

  neo:
    build:
      context: .
      dockerfile: EventBusClient/Dockerfile
    container_name: eventbus-client-neo
    environment:
      - CLIENT_NAME=Neo
      - SERVER_HOST=server
      - SERVER_PORT=9000
    stdin_open: true
    tty: true

  trinity:
    build:
      context: .
      dockerfile: EventBusClient/Dockerfile
    container_name: eventbus-client-trinity
    environment:
      - CLIENT_NAME=Trinity
      - SERVER_HOST=server
      - SERVER_PORT=9000
    stdin_open: true
    tty: true

  morpheus:
    build:
      context: .
      dockerfile: EventBusClient/Dockerfile
    container_name: eventbus-client-morpheus
    environment:
      - CLIENT_NAME=Morpheus
      - SERVER_HOST=server
      - SERVER_PORT=9000
    stdin_open: true
    tty: true

